# Generated by Django 5.1.7 on 2025-03-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Обхват талии')),
                ('chest_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Обхват груди')),
                ('torso_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длина туловища')),
                ('hip_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Обхват бёдер')),
                ('leg_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длина ног')),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длина рукава')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user', verbose_name='Пользователь')),
            ],
        ),
    ]
